server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: abc
    password: abc
    driver-class-name: org.h2.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

   
  
