server:
  port: 8081


spring:

  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: abc
    password: abc
    driver-class-name: org.h2.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8085


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
        
  endpoint:
    health:
      show-details: always
 
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
        
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
        
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    

   
  
